- name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=text-lcov > coverage.lcov

      - name: Upload coverage to CodeClimate
        run: |
          export CC_TEST_REPORTER_ID=${{ secrets.CC_TEST_REPORTER_ID }}
          ./cc-test-reporter after-build --exit-code $?